/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XvancoaAmbulanceWlList {
    }
}
declare global {
    interface HTMLXvancoaAmbulanceWlListElement extends Components.XvancoaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXvancoaAmbulanceWlListElement: {
        prototype: HTMLXvancoaAmbulanceWlListElement;
        new (): HTMLXvancoaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xvancoa-ambulance-wl-list": HTMLXvancoaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XvancoaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xvancoa-ambulance-wl-list": XvancoaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xvancoa-ambulance-wl-list": LocalJSX.XvancoaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXvancoaAmbulanceWlListElement>;
        }
    }
}
